新規登録（お客さん）のポップアップ
fukushima-group/one_plate pull request #10
Opened 2021-04-17 09:48 UTC by WAKUZO

# What

**新規登録（お客さん）のポップアップのビュー**
（トップページから「サインアップ」のボタンを押したときに表示される）

レスポンシブ対応
※ブレイクポイントは仮（sp版はiPhoneXに合わせてます）

2021-04-17 09:51 UTC, WAKUZO commented
Web
<img width="1388" alt="スクリーンショット 2021-04-17 16 43 51" src="https://user-images.githubusercontent.com/58378273/115108867-af0dae00-9fad-11eb-82cf-e0b705a3bc37.png">

Tab
<img width="540" alt="スクリーンショット 2021-04-17 17 03 02" src="https://user-images.githubusercontent.com/58378273/115108868-b2089e80-9fad-11eb-874e-12db1c44d268.png">

sp
<img width="657" alt="スクリーンショット 2021-04-17 16 44 13" src="https://user-images.githubusercontent.com/58378273/115108870-b2a13500-9fad-11eb-8947-8ff9e856f343.png">

2021-04-17 10:05 UTC, WAKUZO commented
Galaxy S5
<img width="457" alt="スクリーンショット 2021-04-17 19 05 23" src="https://user-images.githubusercontent.com/58378273/115109294-e2513c80-9faf-11eb-88fa-0865e9355728.png">

2021-04-17 11:38 UTC, junichi-fukushima commented on frontend/src/components/organisms/Modal/UserAuth/SignUpAuth.tsx
> +  font-size: 14px;
個別の、font-size指定は基本NGでお願いします！
これは、共通のcssを定義しておいて、継承する形にしましょう

(例)
const H4 = styled.h4`
 font-size: 14px;
`;

const SignUpRegisterSubTitle= styled(H4)`

`;

2021-04-17 11:38 UTC, junichi-fukushima commented on frontend/src/components/atoms/Button/BaseButton.tsx
> +  font-size: 14px;
個別の、font-size指定は基本NGでお願いします！
これは、containerとかにかけて消したいです

2021-04-27 01:08 UTC, WAKUZO commented
## フロントー新規登録（お店サイド）

- ウィザード形式

画面遷移：会員情報→店舗情報→確認画面

![react-wizard](https://user-images.githubusercontent.com/58378273/116169740-5c1bbf80-a740-11eb-912d-84f093b2b709.gif)

2021-04-27 01:12 UTC, WAKUZO commented
## 会員情報（エラーメッセージ、正規表現込）

- すべて空はNG
- 代表者氏名：とくに制限なし
- 名前のカナ：「全角カナのみ」
- メールアドレス：「hoge@hoge.comなどを正しく入力」
- パスワード：半角英数字、8文字以上、15文字以内
- パスワード（確認用）：パスワードを一致させるバリデーション、その他はパスワードと同じ制限

![react-wizard-error1](https://user-images.githubusercontent.com/58378273/116169839-8e2d2180-a740-11eb-9503-24bc578a2240.gif)

2021-04-27 01:13 UTC, WAKUZO commented
## 店舗情報（エラーメッセージ、正規表現込）

- すべて空入力NG
- 電話番号：半角英数字

2021-04-28 12:29 UTC, corgimkii commented on frontend/src/components/organisms/Modal/ShopAuth/ShopSignUp.jsx
> +  data: {
以前ペアプロした際に、state更新後に全要素空文字の状態のdataオブジェクトが残るという状況が発生していましたが、ここのdataのネストをなくせば解消されます。
ここのネストを無くすか、またはupdateActionでネストを考慮するかどちらに統一しましょう。

2021-04-28 12:34 UTC, corgimkii commented on frontend/src/components/organisms/Modal/ShopAuth/updateAction.js
> +  console.log("payload:", payload);
上の方で書きましたが、createStoreのネストを活かす場合、書き方は以下のようになります。
```
  return {
    ...state,
    data : {
      ...payload,
    },
  };
```

2021-04-29 23:58 UTC, WAKUZO commented on frontend/src/components/organisms/Modal/ShopAuth/updateAction.js
> +  console.log("payload:", payload);
上記のように修正しました。ご確認お願いします！
コンソールのスクショです。stateの中のdataに値が入りましたが、「会員情報のみ」のデータでよろしいでしょうか？

<img width="1440" alt="スクリーンショット 2021-04-30 8 53 59" src="https://user-images.githubusercontent.com/58378273/116632302-d3945d80-a991-11eb-9a4b-5ba91926c813.png">

<img width="512" alt="スクリーンショット 2021-04-30 8 58 20" src="https://user-images.githubusercontent.com/58378273/116632463-3dad0280-a992-11eb-9dc9-4b5db5676c6e.png">

2021-04-30 12:06 UTC, corgimkii requested changes

2021-04-30 12:06 UTC, corgimkii commented on frontend/src/components/organisms/Modal/ShopAuth/SignUpStep1.jsx
> +            pattern: /^\S+@\S+$/i,
type=emailが効くので、ここのpatternとmessageは使用されることがない気がします。不要かもしれません。

2021-04-30 12:06 UTC, corgimkii commented on frontend/src/components/organisms/Modal/ShopAuth/ShopSignUp.jsx
> +  data: {
以前ペアプロした際に、state更新後に全要素空文字の状態のdataオブジェクトが残るという状況が発生していましたが、ここのdataのネストをなくせば解消されます。
ここのネストを無くすか、またはupdateActionでネストを考慮するかどちらに統一しましょう。

2021-04-30 12:06 UTC, corgimkii commented on frontend/src/components/organisms/Modal/ShopAuth/updateAction.js
> +  console.log("payload:", payload);
@WAKUZO 
こちらの手元で試しましたが、この状態にはなりません。
ちゃんとマージされて「直下にも1階層下にもデータが存在する」状態が解消されるはずです。
そちらの手元でのコードは以下のようになっているでしょうか？
```
// ShopSignUp.jsx
createStore({
  data: {
    …
  }
})

// updateAction.js 
export const updateAction = (state, payload) => {  return {
    ...state,
    data : {
      ...payload,
    },
  };
```
または、
```
// ShopSignUp.jsx
createStore({
    …
})

// updateAction.js 
export const updateAction = (state, payload) => {  return {
    ...state,
    ...payload,
};
```

上記のように修正しても駄目な場合、ブラウザの別タブを開いてやってみてください。
little state machineはセッションストレージに値を保持するので、結果が変わる可能性があります。

2021-05-01 02:25 UTC, WAKUZO commented on frontend/src/components/organisms/Modal/ShopAuth/SignUpStep1.jsx
> +            pattern: /^\S+@\S+$/i,
削除しました

2021-05-01 02:28 UTC, WAKUZO commented on frontend/src/components/organisms/Modal/ShopAuth/ShopSignUp.jsx
> +  data: {
- data: {}　を削除しました。
- updateAciotnのdata:{}を削除しました。

以下のように、stateに入っていたdataオブジェクトが消えました
<img width="1315" alt="スクリーンショット 2021-05-01 11 22 59" src="https://user-images.githubusercontent.com/58378273/116768262-4e33aa80-aa70-11eb-902a-7b210b94af9d.png">

2021-05-15 22:59 UTC, merged